FROM centos:base
MAINTAINER  3x-data information techonology Co, Ltd. - wgzhao
RUN yum install -y http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-1.noarch.rpm
RUN yum install -y postgreql94-server
